# This file configures the analyzer to use the lint rule set from `package:flutter_lints`
include: package:flutter_lints/flutter.yaml

# For more information about the core and recommended set of lints, see
# https://dart.dev/go/core-lints

# Uncomment to specify additional rules:
# linter:
#   rules:
#     - camel_case_types
#     - prefer_single_quotes
#     - sort_child_properties_last

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
