name: runner_code_app
description: "Runner Code - AI-Powered Development Assistant"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number for the application
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies for the application
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  
  # Database dependencies
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  sqflite_common_ffi_web: ^0.4.0
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.3
  
  # HTTP for API calls
  http: ^1.1.0
  
  # Shared preferences for data persistence
  shared_preferences: ^2.2.2
  
  # Speech recognition for voice input
  speech_to_text: ^6.6.0
  
  # Calendar and date picker
  table_calendar: ^3.0.9
  
  # URL launcher for email
  url_launcher: ^6.2.4
  
  # Email sender
  mailer: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Flutter lints for code quality
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # Material design icons
  uses-material-design: true

  # Application assets
  assets:
    - assets/images/

  # Custom fonts can be added here if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
